### ISSUE TITLE
Setup.py file for HSTB gui 

### ISSUE THREAD

**Issue by andrewdavidhydro** [noaa-ocs-hydrography/hstb_gui#1]
Hi guys, 

I've been experimenting with pydro and I am having a hard time installing the HSTB gui module via the command line. Is there supposed to be a setup.py file inside the hstb_gui folder? 

Thanks, 

Andrew

**Comment by barry-gallagher** [comment]
If you are using Pydro it is already installed. It is located in the NOAA/site-packages/python38/git_repos directory. 

The gui module is a set of helper scripts and generally doesn’t use a setup file. Kluster has instructions or installs it straight from GitHub but Pydro has it pre installed
